feat: セッション詳細ページを作成する (#129)
* Speakers から Speaker を find するニーズが発生したので id を追加した

* アバター画像のファイル名を Speaker.id と合わせた

* Speaker を id をもとに取得できるようにした

* new file: src/pages/sessions/_speakerId.vue

* Session を speakerId をもとに取得できるようにした

* ゲストスピーカーのセッション情報を埋めた

* generate.routes を設定した

* sm サイズのレイアウトを整えた

* .speaker に background-color: white を追加した

* セッション詳細ページの内容を Vuex から取得できるようにした

* クラス名を修正した

* md サイズのレイアウトを整えた

* lg サイズのレイアウトを整えた

* .speaker-avatar を可変にした

* FIXME: [Vue warn]: Error in render: "TypeError: Cannot read property '_modulesNamespaceMap' of undefined"

* 仮のデータを Speaker 情報に置き換えた

* TheSpeakerListSection のスピーカー情報を Vuex から取得するようにした

* メタ情報を修正した

* またしても FIXME: TypeError: Cannot read property '_modulesNamespaceMap' of undefined / あとで倒す

* TheSpeakerListSection から不要になった要素を削除した

* fix: TypeError: Cannot read property '_modulesNamespaceMap' of undefined

* Getter デコレーターを使うようにした

* fix: error TS2345: Argument of type 'VueConstructor<Vue>' is not assignable to parameter of type 'FunctionalComponentOptions<Record<string, any>, PropsDefinition<Record<string, any>>>'.

Property 'functional' is missing in type 'VueConstructor<Vue>' but required in type 'FunctionalComponentOptions<Record<string, any>, PropsDefinition<Record<string, any>>>'.

* + speakers!: () => Speaker[]

* fix: 意図せず関数にしていた

* new file: test/unit/specs/utils/createFullStore.ts

* 冗長な書き方をしていたので修正した

* fix: skip を取り忘れていた

* Speaker と Session の情報を埋めた

* HomePage のテストが通るようにした

* description の文言を調整した

* FIXME: [Vue warn]: Error in render: "Error: Session Not Found" / TODO: asyncData の Context.params を指定する方法を調べる

* @Getter デコレーターを使う書き方で統一した

* renamed: test/unit/specs/pages/sessions/speakerId.spec.ts -> test/unit/specs/pages/sessions/_speakerId.spec.ts

* FIXME: Jest でテスト中に asyncData の Context.params を指定する方法が分からない

* インデント方法を全角スペースから Non-Breaking SPace に変更した

* カギカッコを ”” に修正した

* v-html は原則として塞いでおきたいので v-html を局所的に許可するようにした

* ULIVZ さんを追加（詳細が決まるまではコメントアウト）

* session.time を追加

* 毎回 state の型アノテーションを書かなくて良いようにした

* OGP 画像を設定した

* getters の型定義を強制するようにした

* rootState と rootGetters を追加した

* asyncData の型定義を書いた

* Getters の state 以外は必須ではない

* Getters 型を汎用的に使いたいので Vuex の型定義を拡張した

* トップページの SPEAKERS セクションレイアウトを更新した

* 不要な Vue の型拡張を削除した

* 記号を修正しつつ半角スペースを削除

* renamed: test/unit/vue-shims.d.ts -> src/types/vue-shims.d.ts

* インターフェイスのプレフィックスとしての I は、TypeScript の Coding guidelines で使うなと言われている

Coding guidelines · microsoft/TypeScript Wiki
https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines

* Sessions ストアも Speakers と同様に Getters の型定義を強制するようにした

* Revert "Sessions ストアも Speakers と同様に Getters の型定義を強制するようにした"

This reverts commit 1bec486c0e93620ab29665350932c7e23066cca7.

* Sessions ストアも Speakers と同様に Getters の型定義を強制するようにした（再）

* 自分たちで定義した型であることを明示したほうがよさそう

* スピーカー詳細情報へのリンクを追加

* アバター画像にロールオーバー表現を追加した

* ロールオーバー表現にドロップシャドウを追加した

* セッションの ogImage のデフォルト画像を差し替えた

* スピーカー情報、セッション情報を追加した（tejitak）

* 人間 textlint

* fix: セッションページへのリンクに Trailing Slash を入っていない

* .sessiion-time 下の余白を調整した

* 余白の数値調整

* デザイン調整